### PR TITLE
Middleware staging

### PR DESCRIPTION
**Pull request by finnkuusisto**
Initial code for communication between pod, server, and dashboard.

### CODE REVIEW

**Comment by vkottler** [comment]
What's the communication architecture we're going with? Does this contain a python entry-point / main function for the pi and dashboard server respectively?

I notice there are some filenames prefixed `test_`, if we're gonna write networking abstractions on top of the built-in sockets package I think we should consider adding unit testing into the workflow versus manually testing (maybe not now, but when it makes sense)

**Comment by finnkuusisto** [comment]
None of this code interfaces directly with the dashboard yet. There are really two pipes here, both implemented in Python.
1) A UDP receiver/sender pair (sensorreceiverd.py and sensorsenderd.py) for getting sensor data off the pod and into a database. The sender lives on the pod and is responsible for reading the sensor data (to be implemented) repeatedly and sending it to the receiver as a JSON string over UDP. The receiver lives on the NUC and repeatedly reads incoming sensor data off UDP and stores it in the Mongo database.
2) A TCP listener/sender pair (commandreceiverd.py and issue_state_change.py)* for reliably issuing commands to control the pod. The receiver lives on the pod and repeatedly listens for incoming messages over TCP that contain commands issued to the pod (e.g. state change, overrides, etc.). It then executes those commands (to be implemented). The sender is just the one issue_state_change.py script for now, which sends a single state change command to the receiver. That script can really be run from anywhere, but will likely be run from whatever machine is running the dashboard.

*You'll also notice httpcommandreceiver.py and http_issue_state_change.py, which are analogous but operate at the application layer instead using HTTP. This receiver is a web server built on Bottle (a single file web framework) with two endpoints (/state_change and /poke). That is, it provides web endpoints for issuing commands instead of listening directly over TCP. I wrote these because using web endpoints may be slightly easier to communicate with from the dashboard application. http_issue_state_change.py is of course the analogous script that just sends a POST to the /state_change endpoint. It's not yet clear if we'll want to use the HTTP version or the direct TCP version in the final product.

**Comment by vkottler** [comment]
That makes sense, thanks for the response.

UI <--[HTTP]--> NUC backend <--[TCP|UDP]--> Pi

Where the TCP channel is for commands and the UDP channel is for telemetry.

a REST-like API is certainly fast enough for the dashboard. If it's not I'd go with a [websockets](https://github.com/aaugustin/websockets) package instead.

I am going to be helping out on the Pi <-[UART|SPI]--> microcontroller stuff so if you guys could keep me in the loop that'd be awesome!

**Comment by finnkuusisto** [comment]
We'll definitely keep you in the loop. What's the status on SPI stuff? Will we be able to pull all the sensor readings as a big blob that we can package and send to the server?

**Pull request merged**
